### PR TITLE
enhancements for AWS lambda

### PR DESCRIPTION
**Pull request by leoholz**
This branch debugs the AWS support and adds configuration of environment vars and layers.

### CODE REVIEW

**Comment by NathanTP** [comment]
Can you include documentation in docs/ for the user-visible aspects of these changes? At a minimum, it would help me in understanding what changes are being made here and the objectives of those changes. In particular: what are layers?

**Comment by NathanTP** [comment]
Also, you may want to merge master, I made some changes to the docs in #13

**Comment by leoholz** [comment]
> 
> 
> Can you include documentation in docs/ for the user-visible aspects of these changes? At a minimum, it would help me in understanding what changes are being made here and the objectives of those changes. In particular: what are layers?

Of course, thanks for the hint. Please have a look at https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html regarding layers.

I have to admit that I am not sure if I integrated the layers in the right way, but they are basically part of the function provider. If you have other ideas how to integrate them let me know.

**Comment by leoholz** [comment]
master is merged and I added a bit of documentation at Examples.

**Comment by leoholz** [comment]
closing PR as current version is #15

**Pull request closed without merging**
